#!/bin/bash
#
# matryoshka: A VXLAN-over-UDP agent
#
# Copyright (c) 2012 Vangelis Koukis <vkoukis@gmail.com>.
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#


if [ $# -ne 2 ]; then
	cat <<EOF
Usage: $0 tapname vni

Instructs Matryoshka to join virtual network with VNI <vni>,
over local interface <tapname>. The target IP is automatically
allocated from the 239.0.0.0/8 multicast range, based on <vni>.
EOF
	exit 1
fi

cat <<EOF
# Autogenerated by $0 on $(LC_ALL=C date)
TAPNAME=$1
VNI=$2
MACTTL=20
#TARGETIP=192.168.2.255
TARGETIP=$(python -c "import sys;import IPy; print IPy.IP(0xEF000000 + $2)")
TARGETPORT=3601
EOF
